spring:
  jpa:
    #    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
#    data: data.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/shop
    username: root
    password: Mysql123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_PASSWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true